/**
 * Dados iniciais para população do Banco de Dados MySQL
 */
export const SEED_USERS = [
  {
    id: 'user-admin',
    name: 'Admin Guia Sabor',
    email: 'admin@guiasabor.com.br',
    password_hash: 'admin123',
    role: 'admin',
    created_at: '01/01/2026',
  },
  {
    id: 'user-demo',
    name: 'Usuário Convidado',
    email: 'usuario@exemplo.com',
    password_hash: '123456',
    role: 'user',
    created_at: '01/01/2026',
  },
]

export const SEED_RESTAURANTS = [
  {
    id: 'rest-1',
    name: 'Cantina Bella Italia',
    cuisine: 'Italiana',
    address: 'Rua das Oliveiras, 142 - Cambuí',
    city: 'Campinas',
    hours: 'Ter - Dom: 11h30 às 23h00',
    rating: 4.8,
    phone: '(19) 3254-8890',
    website: 'https://cantinabellaitalia.com.br',
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80',
    description: 'Massas artesanais frescas preparadas diariamente seguindo receitas tradicionais da Toscana em ambiente aconchegante e romântico.',
    priceRange: 'R$$$',
    cnpj: '12.345.678/0001-95',
    legalName: 'Bella Italia Gastronomia & Vinhos Ltda.',
    isVerified: true,
    verificationStatus: 'verified',
    verifiedDate: '15/01/2026',
    verifiedBy: 'Equipe de Segurança & Compliance Guia Sabor',
    safetyScore: 99,
    reportCount: 0,
    amenities: ['Wi-Fi Grátis', 'Ar Condicionado', 'Carta de Vinhos', 'Aceita Reservas', 'Estacionamento com Manobrista', 'Área Externa'],
    verifiedBadges: [
      '🛡️ CNPJ Regular na Receita Federal',
      '📍 Endereço Comercial Físico Confirmado',
      '📞 Telefone Oficial de Atendimento Validado',
      '🔒 Proteção Anti-Fraude & Pagamento Seguro',
    ],
    menu: [
      {
        id: 'm1-1',
        name: 'Bruschetta Tradizionale',
        description: 'Pão italiano tostado, tomates marinados com manjericão fresco, alho e azeite extravirgem.',
        price: 34.9,
        category: 'Entradas',
        isVegetarian: true,
        image: 'https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?auto=format&fit=crop&w=800&q=80',
      },
      {
        id: 'm1-2',
        name: 'Carpaccio di Manzo',
        description: 'Finas lâminas de filé mignon, molho de alcaparras, lascas de parmesão e rúcula.',
        price: 46.0,
        category: 'Entradas',
        isPopular: true,
        image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
      },
      {
        id: 'm1-3',
        name: 'Fettuccine al Tartufo',
        description: 'Massa fresca caseira envolvida em emulsão cremosa de manteiga trufada e cogumelos porcini.',
        price: 78.5,
        category: 'Pratos Principais',
        isPopular: true,
        image: 'https://images.unsplash.com/photo-1621996346565-e3d5d6281084?auto=format&fit=crop&w=800&q=80',
      },
      {
        id: 'm1-4',
        name: 'Gnocchi alla Sorrentina',
        description: 'Nhoque artesanal de batata ao molho de tomate San Marzano, muçarela de búfala e manjericão.',
        price: 64.0,
        category: 'Pratos Principais',
        isVegetarian: true,
        image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=800&q=80',
      },
      {
        id: 'm1-5',
        name: 'Tiramisù Clássico',
        description: 'Camadas de biscoito savoiardi embebidas em café expresso e licor amaretto, creme de mascarpone e cacau.',
        price: 29.0,
        category: 'Sobremesas',
        isPopular: true,
        image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=800&q=80',
      },
      {
        id: 'm1-6',
        name: 'Vinho Chianti Classico DOCG (Garrafa)',
        description: 'Vinho tinto italiano encorpado com notas de cerejas maduras e toques de especiarias.',
        price: 145.0,
        category: 'Bebidas',
        image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=800&q=80',
      },
    ],
    reviews: [
      {
        id: 'rev-1',
        author: 'Mariana Silva',
        stars: 5,
        comment: 'O melhor fettuccine ao molho trufado que já provei! Atendimento impecável.',
        createdAt: '15/08/2026',
      },
      {
        id: 'rev-2',
        author: 'Carlos Alberto',
        stars: 4,
        comment: 'Ambiente aconchegante e carta de vinhos excelente. Recomendo reservar aos finais de semana.',
        createdAt: '10/08/2026',
      },
    ],
  },
  {
    id: 'rest-2',
    name: 'Sakura Sushi Lounge',
    cuisine: 'Japonesa',
    address: 'Av. Paulista, 1850 - Bela Vista',
    city: 'São Paulo',
    hours: 'Seg - Sáb: 12h00 às 23h30',
    rating: 4.9,
    phone: '(11) 3145-2020',
    website: 'https://sakurasushilounge.com.br',
    image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=1200&q=80',
    description: 'Experiência Omakase contemporânea com peixes frescos nobres selecionados e sushis autorais.',
    priceRange: 'R$$$$',
    cnpj: '23.456.789/0001-95',
    legalName: 'Sakura Gastronomia Oriental & Eventos Eireli',
    isVerified: true,
    verificationStatus: 'verified',
    verifiedDate: '10/01/2026',
    verifiedBy: 'Equipe de Segurança & Compliance Guia Sabor',
    safetyScore: 100,
    reportCount: 0,
    amenities: ['Wi-Fi Grátis', 'Ar Condicionado', 'Balcão Omakase', 'Carta de Sakês', 'Acessibilidade', 'Opções Veganas'],
    verifiedBadges: [
      '🛡️ CNPJ Regular na Receita Federal',
      '📍 Endereço Comercial Físico Confirmado',
      '📞 Telefone Oficial de Atendimento Validado',
      '🔒 Proteção Anti-Fraude & Pagamento Seguro',
    ],
    menu: [
      {
        id: 'm2-1',
        name: 'Sunomono Especial com Polvo',
        description: 'Finas lâminas de pepino agridoce com fatias de polvo macio e sementes de gergelim tostadas.',
        price: 38.0,
        category: 'Entradas',
        image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80',
      },
      {
        id: 'm2-2',
        name: 'Combo Omakase Premium (18 peças)',
        description: 'Seleção do chef: nigiris de atum bluefin, salmão selado com trufas, vieira fresca e uramakis autorais.',
        price: 135.0,
        category: 'Pratos Principais',
        isPopular: true,
        image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=800&q=80',
      },
      {
        id: 'm2-3',
        name: 'Sashimi de Salmão Trufado',
        description: '12 lâminas de salmão fresco maçaricado com azeite trufado, flor de sal e raspas de limão siciliano.',
        price: 72.0,
        category: 'Pratos Principais',
        isPopular: true,
        image: 'https://images.unsplash.com/photo-1611143669185-af224c5e3252?auto=format&fit=crop&w=800&q=80',
      },
      {
        id: 'm2-4',
        name: 'Mochi Artesanal de Chá Verde',
        description: 'Massa elástica de arroz recheada com sorvete de matcha orgânico.',
        price: 24.0,
        category: 'Sobremesas',
        image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=800&q=80',
      },
      {
        id: 'm2-5',
        name: 'Sakê Junmai Ginjo (Dose 150ml)',
        description: 'Sakê japonês premium importado, leve e floral com final refrescante.',
        price: 42.0,
        category: 'Bebidas',
        image: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?auto=format&fit=crop&w=800&q=80',
      },
    ],
    reviews: [
      {
        id: 'rev-3',
        author: 'Felipe Taniguchi',
        stars: 5,
        comment: 'Nigiris perfeitos e apresentação de alto nível. Um verdadeiro festival para o paladar.',
        createdAt: '17/08/2026',
      },
      {
        id: 'rev-4',
        author: 'Juliana Costa',
        stars: 5,
        comment: 'Festival maravilhoso e atendimento rápido. O sashimi de salmão selado com azeite trufado é divino!',
        createdAt: '12/08/2026',
      },
    ],
  },
  {
    id: 'rest-3',
    name: 'Fogão de Minas & Raízes',
    cuisine: 'Brasileira',
    address: 'Av. Barão de Itapura, 920 - Guanabara',
    city: 'Campinas',
    hours: 'Ter - Dom: 11h00 às 16h00',
    rating: 4.6,
    phone: '(19) 3233-4411',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=1200&q=80',
    amenities: ['Fogão a Lenha', 'Estacionamento Próprio', 'Espaço Kids', 'Ambiente Familiar', 'Pet Friendly'],
    description: 'A autêntica culinária caipira e mineira servida em fogão a lenha com sobremesas caseiras típicas.',
    priceRange: 'R$$',
    cnpj: '34.567.890/0001-30',
    legalName: 'Fogão de Minas Restaurante Tradicional Ltda.',
    isVerified: true,
    verificationStatus: 'verified',
    verifiedDate: '18/01/2026',
    verifiedBy: 'Equipe de Segurança & Compliance Guia Sabor',
    safetyScore: 98,
    reportCount: 0,
    verifiedBadges: [
      '🛡️ CNPJ Regular na Receita Federal',
      '📍 Endereço Comercial Físico Confirmado',
      '📞 Telefone Oficial de Atendimento Validado',
      '🔒 Proteção Anti-Fraude & Pagamento Seguro',
    ],
    menu: [
      {
        id: 'm3-1',
        name: 'Torresmo de Rolo Crocante',
        description: 'Porção generosa de torresmo pururuca com geleia caseira de pimenta da casa.',
        price: 42.0,
        category: 'Entradas',
        isPopular: true,
        image: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=800&q=80',
      },
      {
        id: 'm3-2',
        name: 'Feijão Tropeiro Tradicional Completo',
        description: 'Feijão carioca, farinha de mandioca na manteiga, torresmo, ovos, couve refogada e bisteca de porco.',
        price: 58.0,
        category: 'Pratos Principais',
        isPopular: true,
        image: 'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=800&q=80',
      },
      {
        id: 'm3-3',
        name: 'Frango com Quiabo Caipira',
        description: 'Frango cozido lentamente com quiabo sem baba e polenta cremosa feita no fubá de moinho d’água.',
        price: 54.0,
        category: 'Pratos Principais',
        image: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&w=800&q=80',
      },
      {
        id: 'm3-4',
        name: 'Doce de Leite com Queijo Minas',
        description: 'Doce de leite pastoso artesanal de tacho de cobre servido com fatia generosa de queijo canastra.',
        price: 22.0,
        category: 'Sobremesas',
        isPopular: true,
        image: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&w=800&q=80',
      },
      {
        id: 'm3-5',
        name: 'Caipirinha de Cachaça da Serra',
        description: 'Feita com cachaça envelhecida em barris de carvalho, limão taiti e rapadura ralada.',
        price: 26.0,
        category: 'Bebidas',
        image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=800&q=80',
      },
    ],
    reviews: [
      {
        id: 'rev-5',
        author: 'Rodrigo Mendonça',
        stars: 5,
        comment: 'Feijão tropeiro e torresmo crocante no ponto certo. Lembra a comida da minha avó!',
        createdAt: '14/08/2026',
      },
      {
        id: 'rev-6',
        author: 'Ana Paula Ramos',
        stars: 4,
        comment: 'Comida muito saborosa e farta. Chegue cedo porque a fila costuma ser grande.',
        createdAt: '08/08/2026',
      },
    ],
  },
  {
    id: 'rest-4',
    name: 'The Iron Burger Smokehouse',
    cuisine: 'Hamburgueria',
    address: 'Rua Augusta, 2210 - Jardins',
    city: 'São Paulo',
    hours: 'Todos os dias: 17h00 às 01h00',
    rating: 4.7,
    phone: '(11) 3062-8877',
    website: 'https://theironburger.com.br',
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=1200&q=80',
    amenities: ['Música ao Vivo / Rock', 'Wi-Fi Grátis', 'Cervejas Artesanais', 'Delivery Rápido', 'Ar Condicionado'],
    description: 'Burgers artesanais defumados na lenha de macieira com queijos fundidos e pães brioche tostados na manteiga.',
    priceRange: 'R$$',
    cnpj: '45.678.901/0001-75',
    legalName: 'Iron Smokehouse Burger Bar & Grill Ltda.',
    isVerified: true,
    verificationStatus: 'verified',
    verifiedDate: '22/01/2026',
    verifiedBy: 'Equipe de Segurança & Compliance Guia Sabor',
    safetyScore: 98,
    reportCount: 0,
    verifiedBadges: [
      '🛡️ CNPJ Regular na Receita Federal',
      '📍 Endereço Comercial Físico Confirmado',
      '📞 Telefone Oficial de Atendimento Validado',
      '🔒 Proteção Anti-Fraude & Pagamento Seguro',
    ],
    menu: [
      {
        id: 'm4-1',
        name: 'Batata Rústica Defumada com Páprica',
        description: 'Batatas com corte artesanal crocantes por fora, com alecrim, alho assado e maionese trufada.',
        price: 32.0,
        category: 'Entradas',
        isPopular: true,
        isVegetarian: true,
        image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=800&q=80',
      },
      {
        id: 'm4-2',
        name: 'Smoked Bacon Cheddar Burger',
        description: 'Blend bovino 180g defumado no pit, cheddar inglês cremoso, tiras grossas de bacon artesanal e barbecue.',
        price: 45.0,
        category: 'Pratos Principais',
        isPopular: true,
        image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80',
      },
      {
        id: 'm4-3',
        name: 'Truffle Mushroom Burger (Veggie)',
        description: 'Hambúrguer de cogumelos portobello empanados, queijo provolone derretido e rúcula baby.',
        price: 43.0,
        category: 'Pratos Principais',
        isVegetarian: true,
        image: 'https://images.unsplash.com/photo-1525059696034-4967a8e1dca2?auto=format&fit=crop&w=800&q=80',
      },
      {
        id: 'm4-4',
        name: 'Brownie com Sorvete de Baunilha',
        description: 'Brownie denso de chocolate 70% belga com calda quente de caramelo salgado e nozes.',
        price: 28.0,
        category: 'Sobremesas',
        image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=800&q=80',
      },
      {
        id: 'm4-5',
        name: 'Chopp IPA Artesanal (Pint 500ml)',
        description: 'Cerveja artesanal fresca com lúpulos aromáticos cítricos e amargor equilibrado.',
        price: 22.0,
        category: 'Bebidas',
        image: 'https://images.unsplash.com/photo-1608270191722-1d54e4a78cb5?auto=format&fit=crop&w=800&q=80',
      },
    ],
    reviews: [
      {
        id: 'rev-7',
        author: 'Lucas Ferreira',
        stars: 5,
        comment: 'Smash burger suculento e batatas rústicas com páprica que são viciantes!',
        createdAt: '16/08/2026',
      },
      {
        id: 'rev-8',
        author: 'Beatriz Lima',
        stars: 4,
        comment: 'Excelente maionese de alho negro e ambiente descontraído com boa música.',
        createdAt: '11/08/2026',
      },
    ],
  },
  {
    id: 'rest-5',
    name: 'Trattoria del Nonno',
    cuisine: 'Italiana',
    address: 'Rua Treze de Maio, 550 - Bixiga',
    city: 'São Paulo',
    hours: 'Qua - Dom: 12h00 às 22h30',
    rating: 4.5,
    phone: '(11) 3288-9900',
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80',
    amenities: ['Música Tradicional Italiana', 'Carta de Vinhos', 'Salão Clássico', 'Aceita Reservas', 'Ar Condicionado'],
    description: 'Tradição italiana centenária no coração do Bixiga com lasanhas generosas e polpetone recheado com queijo derretido.',
    priceRange: 'R$$$',
    cnpj: '56.789.012/0001-00',
    legalName: 'Trattoria del Nonno Cantina Italiana Eireli',
    isVerified: true,
    verificationStatus: 'verified',
    verifiedDate: '05/01/2026',
    verifiedBy: 'Equipe de Segurança & Compliance Guia Sabor',
    safetyScore: 97,
    reportCount: 0,
    verifiedBadges: [
      '🛡️ CNPJ Regular na Receita Federal',
      '📍 Endereço Comercial Físico Confirmado',
      '📞 Telefone Oficial de Atendimento Validado',
      '🔒 Proteção Anti-Fraude & Pagamento Seguro',
    ],
    menu: [
      {
        id: 'm5-1',
        name: 'Polpetone Recheado com Muçarela',
        description: 'Grande almôndega de carne recheada com queijo derretido coberta por molho rústico de tomate e manjericão.',
        price: 74.0,
        category: 'Pratos Principais',
        isPopular: true,
        image: 'https://images.unsplash.com/photo-1529042410759-befb1204b468?auto=format&fit=crop&w=800&q=80',
      },
      {
        id: 'm5-2',
        name: 'Lasanha à Bolonhesa da Nona',
        description: 'Camadas de massa fresca com ragu de carnes selecionadas e molho bechamel gratinado.',
        price: 66.0,
        category: 'Pratos Principais',
        isPopular: true,
        image: 'https://images.unsplash.com/photo-1574894709920-11b28e7367e3?auto=format&fit=crop&w=800&q=80',
      },
      {
        id: 'm5-3',
        name: 'Cannoli Siciliano',
        description: 'Massa crocante frita recheada com creme de ricota doce, raspas de laranja e gotas de chocolate.',
        price: 18.0,
        category: 'Sobremesas',
        isPopular: true,
        image: 'https://images.unsplash.com/photo-1551106652-a5bcf4b29ab6?auto=format&fit=crop&w=800&q=80',
      },
    ],
    reviews: [
      {
        id: 'rev-9',
        author: 'Eduardo Martins',
        stars: 5,
        comment: 'O polpetone com queijo derretendo é simplesmente lendário!',
        createdAt: '05/08/2026',
      },
    ],
  },
  {
    id: 'rest-6',
    name: 'Sabor do Sertão',
    cuisine: 'Brasileira',
    address: 'Rua Coronel Quirino, 680 - Cambuí',
    city: 'Campinas',
    hours: 'Ter - Dom: 11h30 às 22h00',
    rating: 4.7,
    phone: '(19) 3251-7766',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=80',
    amenities: ['Música Nordestina', 'Wi-Fi Grátis', 'Ambiente Climatizado', 'Aceita Cartões e Pix', 'Espaço Aconchegante'],
    description: 'Especialidades nordestinas autênticas: baião de dois, carne de sol na nata, macaxeira frita e bobó de camarão.',
    priceRange: 'R$$',
    cnpj: '67.890.123/0001-16',
    legalName: 'Sabor do Sertão Culinária Típica Ltda.',
    isVerified: true,
    verificationStatus: 'verified',
    verifiedDate: '12/01/2026',
    verifiedBy: 'Equipe de Segurança & Compliance Guia Sabor',
    safetyScore: 99,
    reportCount: 0,
    verifiedBadges: [
      '🛡️ CNPJ Regular na Receita Federal',
      '📍 Endereço Comercial Físico Confirmado',
      '📞 Telefone Oficial de Atendimento Validado',
      '🔒 Proteção Anti-Fraude & Pagamento Seguro',
    ],
    menu: [
      {
        id: 'm6-1',
        name: 'Dadinhos de Tapioca com Queijo Coalho',
        description: 'Cubos crocantes de tapioca e queijo coalho servidos com geleia de pimenta defumada.',
        price: 36.0,
        category: 'Entradas',
        isPopular: true,
        isVegetarian: true,
        image: 'https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?auto=format&fit=crop&w=800&q=80',
      },
      {
        id: 'm6-2',
        name: 'Baião de Dois Especial com Queijo Coalho',
        description: 'Arroz, feijão de corda, carne seca desfiada, bacon, queijo coalho grelhado e manteiga de garrafa.',
        price: 68.0,
        category: 'Pratos Principais',
        isPopular: true,
        image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80',
      },
      {
        id: 'm6-3',
        name: 'Bobó de Camarão Baiano',
        description: 'Camarões médios em creme aveludado de mandioca com azeite de dendê, leite de coco e coentro.',
        price: 82.0,
        category: 'Pratos Principais',
        image: 'https://images.unsplash.com/photo-1559742811-822873691df8?auto=format&fit=crop&w=800&q=80',
      },
      {
        id: 'm6-4',
        name: 'Cocada Cremosa de Colher com Sorvete',
        description: 'Cocada quente de coco fresco ralado com sorvete de tapioca.',
        price: 26.0,
        category: 'Sobremesas',
        isPopular: true,
        image: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&w=800&q=80',
      },
    ],
    reviews: [
      {
        id: 'rev-10',
        author: 'Camila Nogueira',
        stars: 5,
        comment: 'O baião de dois cremoso e a macaxeira frita estavam perfeitos.',
        createdAt: '13/08/2026',
      },
    ],
  },
]
